version: '3.7'

services:
  # Arango DB
  db:
    image: arangodb:3.6.0
    container_name: bot-db
    restart: on-failure
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PWD}
    ports:
      - 8529:8529
    volumes:
      - ./arangodb:/data

  # Python bot app
  app:
    image: tvshows-bot
    container_name: bot-app
    build: ../src
    env_file: env-file
    command: python bot_app.py
    depends_on:
      - db
