version: '3.7'

services:
  # Arango DB
  db:
    image: arangodb:3.6.0
    container_name: bot-db
    restart: on-failure
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - 8529:8529

  # Python bot app
  app:
    image: tvshows-bot
    container_name: bot-app
    build: ../src
    env_file: env-file
    command: python bot_app.py
    ports:
      - 9706:9706
    volumes:
      - ../src:/tvshows-bot
    depends_on:
      - db
